class NaListeningDataView(object):
    section1 = [{"html":"/",
	          "img" :"https://media-cdn.tripadvisor.com/media/photo-s/03/9b/2e/01/punta-cana.jpg",
			  "caption":"Food"},
	         {"html":"/reading",
			  "img" :"https://static.tacdn.com/img2/vacationrentals/lander/popularGeos/Gatlinburg cabins.jpg",
			  "caption":"Traveling"},
			 {"html":"/listening",
			  "img" :"https://static.tacdn.com/img2/vacationrentals/lander/popularGeos/Key West vacation rentals.jpg",
			  "caption":"Work"} ]
    section2 = [{"html":"/",
	          "img" :"https://media-cdn.tripadvisor.com/media/photo-s/03/9b/2e/01/punta-cana.jpg",
			  "caption":"Happiness"},
	         {"html":"/reading",
			  "img" :"https://static.tacdn.com/img2/vacationrentals/lander/popularGeos/Gatlinburg cabins.jpg",
			  "caption":"Traveling"},
			 {"html":"/listening",
			  "img" :"https://static.tacdn.com/img2/vacationrentals/lander/popularGeos/Key West vacation rentals.jpg",
			  "caption":"Work"} ]
    section3 = [{"html":"/",
	          "img" :"https://media-cdn.tripadvisor.com/media/photo-s/03/9b/2e/01/punta-cana.jpg",
			  "caption":"Food"},
	         {"html":"/reading",
			  "img" :"https://static.tacdn.com/img2/vacationrentals/lander/popularGeos/Gatlinburg cabins.jpg",
			  "caption":"Traveling"},
			 {"html":"/listening",
			  "img" :"https://static.tacdn.com/img2/vacationrentals/lander/popularGeos/Key West vacation rentals.jpg",
			  "caption":"Work"} ]
    section4 = [{"html":"/",
	          "img" :"https://media-cdn.tripadvisor.com/media/photo-s/03/9b/2e/01/punta-cana.jpg",
			  "caption":"Food"},
	         {"html":"/reading",
			  "img" :"https://static.tacdn.com/img2/vacationrentals/lander/popularGeos/Gatlinburg cabins.jpg",
			  "caption":"Traveling"},
			 {"html":"/listening",
			  "img" :"https://static.tacdn.com/img2/vacationrentals/lander/popularGeos/Key West vacation rentals.jpg",
			  "caption":"Work"} ]